import type { Match } from './types';

export const allMatches: Match[] = [
  {
    id: 1,
    sport: 'Basketball',
    location: 'Golden Gate Park',
    district: 'San Francisco',
    dateTime: new Date(new Date().setDate(new Date().getDate() + 2)),
    playersJoined: 3,
    playersNeeded: 10,
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d',
    organizer: 'Alex D.',
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 2,
    sport: 'Soccer',
    location: 'Prospect Park',
    district: 'Brooklyn',
    dateTime: new Date(new Date().setDate(new Date().getDate() + 3)),
    playersJoined: 8,
    playersNeeded: 16,
    avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    organizer: 'Maria G.',
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 3,
    sport: 'Tennis',
    location: 'Lincoln Park',
    district: 'Chicago',
    dateTime: new Date(new Date().setDate(new Date().getDate() + 1)),
    playersJoined: 1,
    playersNeeded: 2,
    avatar: 'https://i.pravatar.cc/150?u=a04258114e29026702d',
    organizer: 'Sam T.',
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 4,
    sport: 'Basketball',
    location: 'Venice Beach Courts',
    district: 'Los Angeles',
    dateTime: new Date(new Date().setDate(new Date().getDate() + 5)),
    playersJoined: 5,
    playersNeeded: 10,
    avatar: 'https://i.pravatar.cc/150?u=a048581f4e29026701d',
    organizer: 'Chris P.',
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 5,
    sport: 'Soccer',
    location: 'Zilker Park',
    district: 'Austin',
    dateTime: new Date(new Date().setDate(new Date().getDate() + 4)),
    playersJoined: 12,
    playersNeeded: 22,
    avatar: 'https://i.pravatar.cc/150?u=b042581f4e29026704d',
    organizer: 'Jessica W.',
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 6,
    sport: 'Tennis',
    location: 'Crandon Park',
    district: 'Miami',
    dateTime: new Date(new Date().setDate(new Date().getDate() + 2)),
    playersJoined: 1,
    playersNeeded: 4,
    avatar: 'https://i.pravatar.cc/150?u=c042581f4e29026702d',
    organizer: 'Mike L.',
    image: 'https://placehold.co/600x400.png',
  },
];
